rosplan_demo_waypoints:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    wp0: [0.1250, -0.0749, 0.0]
    wp1: [-1.0073, -1.7235, 0.0]
    wp2: [-1.2921, 0.2561, 0.0]
    wp3: [-0.8249, -3.6249, 0.0]
    wp4: [0.6861, -1.9946, 0.0]
    wp5: [0.6316, 0.8029, 0.0]
