sudo: required
dist: bionic
language: generic

env:
  global:
    - ROS_DISTRO=melodic
    - WRITABLE_SOURCE=true # allow the creation of files inside src
    - NOT_TEST_INSTALL=true # skip install space unit tests

before_install:
    - bash ./.travis/wait_for_apt.sh
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install libcurl3
    - sudo apt-get install flex bison ros-melodic-tf2-bullet
    - sudo apt-get install libbdd-dev
    - git clone --recurse-submodules --recursive https://github.com/KCL-Planning/ROSPlan.git
    - git clone https://github.com/clearpathrobotics/occupancy_grid_utils
    - git submodule update --init --remote --recursive

install:
  - git clone --depth=1 --branch legacy-writable https://github.com/oscar-lima/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
