# x, y, radius, std_dev
doughnuts:
  - {name: 'p01', x: 4.17, y: 38.8, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p02', x: 4.57, y: 38.8, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p03', x: 4.97, y: 38.8, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p04', x: 4.01, y: 30.6, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p05', x: 2.37, y: 22.8, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p06', x: 3.94, y: 12.8, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p07', x: 23.6, y: 13.4, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p08', x: 23.8, y: 18.3, radius: 1.3, std_dev: 0.30, type: 'pedestal'}
  - {name: 'p09', x: 23.9, y: 23.4, radius: 1.3, std_dev: 0.30, type: 'pedestal'}

# Specify the arc of form [x, y, radius, angle, arclength (radians), std_dev]
bananas:
  - {name: '', x: 22.3, y: 35.8, radius: 0.75, angle: 0,  arclen: 1, std_dev: 0.15, type: ''}
  - {name: '', x: 27.6, y: 32.3, radius: 0.75, angle: 1.57, arclen:  0.5, std_dev: 0.15, type: ''}
  - {name: '', x: 23.7, y: 32.3, radius: 1.5, angle: 0, arclen:  1.5, std_dev: 0.3, type: ''}
  - {name: '', x: 23.7, y: 33.3, radius: 1.5, angle: 1.57, arclen:  1.5, std_dev: 0.15, type: ''}
  - {name: '', x: 18.6, y: 32.3, radius: 0.75, angle: 3.14159265359, arclen:  1, std_dev: 0.15, type: ''}
  - {name: '', x: 23.7, y: 30.6, radius: 1.5, angle: 0, arclen:  2.5, std_dev: 0.15, type: ''}
