functions:
    - $(find rosplan_demo_stage)/scripts/sampling_sensing_functions.py
topics:
    doughnut_visible_from:
        params:
            - '*'
            - '*'
        topic: /update_visibility
        msg_type: std_msgs/String
