# For reachable objects
# Specify the torus of form [x, y, radius]
doughnuts:
- [8.91,0.54,0.50]
- [10.7,0.49,0.50]
- [9.71,1.27,0.50]

# For observable objects
# Specify the arc of form [x, y, radius, angle, arclength (radians)]
bananas:
- [0.00,9.83,1.75,0.00,1.04]
- [0.00,8.65,1.75,0.00,1.04]
- [0.00,7.28,1.75,0.00,1.04]
