# For reachable objects
# Specify the torus of form [x, y, radius, std_Dev]
doughnuts:
- [8.91,0.54,0.50, 0.75]
- [10.7,0.49,0.50, 0.5]
- [9.71,1.27,0.50, 0.5]

# For observable objects
# Specify the arc of form [x, y, radius, angle, arclength (radians), std_dev]
bananas:
- [0.00,9.83,1.75,-1.5708,1.75, 0.15]
- [6.00,6,1.75,-1.5708,1.04,0.15]
- [0.00,7.28,1.75,-1.5708,1, 0.05]
