name: build

on: [push, pull_request]

env:
  ROS_VERSION: melodic
jobs:
  build:
    runs-on: ubuntu-latest    
    container:
      image: ros:melodic
    steps:
      - name: Prepare docker
        run: |
          # Install newer git from ppa to prevent https://github.com/actions/checkout/issues/126
          APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true apt-key adv --keyserver keyserver.ubuntu.com --recv-key E1DD270288B4E6030699E45FA1715D88E1DF1F24 2>&1
          echo "deb http://ppa.launchpad.net/git-core/ppa/ubuntu bionic main" | tee /etc/apt/sources.list.d/git.list 
          sudo apt update -qq
          sudo apt install python-catkin-tools git -y -qq
      - name: Create ROS workspace
        run: |
          source /opt/ros/$ROS_VERSION/setup.bash
          mkdir src
          catkin init
          catkin build --summarize  --no-status
        shell: bash
      - name: "Checkout source"
        uses: actions/checkout@v2
        with:
          path: src/rosplan_demos
      - name: Checkout ROSPlan and submodules
        shell: bash
        run: |
          git clone --recurse-submodules --recursive https://github.com/KCL-Planning/ROSPlan.git --depth 1 src/rosplan
          git clone https://github.com/clearpathrobotics/occupancy_grid_utils --depth 1 src/occupancy_grid_utils
          cd src/rosplan_demos
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install dependencies
        run: |
          source devel/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -q -r -y
        shell: bash
      - name: Build workspace
        run: catkin build --summarize # --no-status

